#!/bin/bash
### BEGIN INIT INFO
# Provides:          my-custom-service-runner
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: My Custom Service
# Description:       This script starts the actions runner using init.d boot system, instead of systemd.
### END INIT INFO

start() {
    cd /home/peter/actions-runner
    ./bin/runsvc.sh /etc/init.d/actions.runner.service.template
}

stop() {
    pkill -f "my-custom-service-runner"
    echo "Service stopped"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 1
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
esac