name: Build Project [Install, Build, Run]

on:
  push:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: self-hosted

    env:
      # Update $HOME to match the self-hosted machine for Go paths.
      # This would not be a problem with GitHub hosted machines.
      HOME: /home/peter

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install g++ git python3 python3-pip libgtest-dev

    - name: Download Libraries
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        # Optional, the status or conclusion of a completed workflow to search for
        # Can be one of a workflow conclusion:
        #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
        # Or a workflow status:
        #   "completed", "in_progress", "queued"
        # Use the empty string ("") to ignore status or conclusion in the search
        workflow_conclusion: success
        workflow: build_libraries.yaml
        if_no_artifact_found: fail
        name: libraries
        path: .

    - name: Extract Artifact
      run: tar xzf libraries.tar.gz

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21.6
      id: go

    - name: Display Installed Versions
      run: |
        g++ --version
        git --version
        python3 --version
        pip3 --version
        go version

    - name: Run Tests
      run: |
        python3 test_runner.py --language all

    - name: Check Test Status
      run: |
        if [ $? -ne 0 ]; then
          echo "Tests failed. Failing the workflow."
          exit 1
        fi
