name: Build Libraries

# on:
#   push:
#     branches:
#       - main

# Manual trigger
on:
  workflow_dispatch:

jobs:
  build_libraries:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install tar gzip cmake g++ git python3 python3-pip libgtest-dev

          # Install Python packages using pip
          pip3 install cget

          # Install user's private bin path for cget
          PROFILE_DIR="$HOME/.profile"
          source $PROFILE_DIR

          # Install dependencies [JSON, boost] using cget
          cget install https://github.com/nlohmann/json/archive/refs/tags/v3.11.3.tar.gz
          cget install https://github.com/boostorg/boost/releases/download/boost-1.84.0/boost-1.84.0.tar.gz

      - name: Create Archive
        run: tar czf libraries.tar.gz cget

      - name: Display Installed Versions
        run: |
          cmake --version
          g++ --version
          git --version
          python3 --version
          pip3 --version
          cget --version
          
      - name: Archive Libraries
        uses: actions/upload-artifact@v3
        with:
          name: libraries
          path: libraries.tar.gz
