name: Build Project [Install, Build, Run]

on:
  push:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: self-hosted

    env:
      # Update $HOME to match the self-hosted machine for Go paths.
      # This would not be a problem with GitHub hosted machines.
      HOME: /home/peter

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install g++ git python3 python3-pip libgtest-dev

        # Install Python packages using pip
        pip3 install cget

        # Install dependencies using cget
        #cget install https://github.com/nlohmann/json/archive/refs/tags/v3.11.3.tar.gz
        #cget install https://github.com/boostorg/boost/releases/download/boost-1.84.0/boost-1.84.0.tar.gz

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21.6
      id: go

    - name: Display Installed Versions
      run: |
        g++ --version
        git --version
        python3 --version
        pip3 --version
        #cget --version
        go version

    - name: Run Tests
      run: python3 test_runner.py

    - name: Check Test Status
      run: |
        if [ $? -ne 0 ]; then
          echo "Tests failed. Failing the workflow."
          exit 1
        fi
