name: Build Project [Install, Build, Run]

on:
  push:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Permissions
      run: chmod +x install.sh

    - name: Install Dependencies
      run: ./install.sh

    - name: Run Tests
      run: python3 test_runner.py
