name: Build Project [Install, Build, Run]

on:
  push:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        chmod +x install.sh
        ./install.sh
      working-directory: ${{ github.workspace }}

    - name: Run Tests
      run: python3 test_runner.py
