name: Build Project [Install, Build, Run]

on:
  push:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: self-hosted

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Permissions
      run: chmod +x install.sh

    - name: Install Dependencies
      run: ./install.sh

    - name: Update PATH
      run: |
        # if [[ ":$PATH:" != *":/usr/local/go/bin:"* ]]; then
        echo 'export PATH=$PATH:/usr/local/go/bin' >> $HOME/.bashrc
        source $HOME/.bashrc
        # fi

    - name: Run Tests
      run: python3 test_runner.py

    - name: Check Test Status
      run: |
        if [ $? -ne 0 ]; then
          echo "Tests failed. Failing the workflow."
          exit 1
        fi
