name: Build Libraries

on:
  # Manual trigger
  workflow_dispatch:
  # Schedule
  schedule:
    - cron: '0 17 * * *'  # Run every day at 12 PM (noon) EST (5 PM UTC)

jobs:
  build_libraries:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install tar gzip cmake g++ git python3 python3-pip libgtest-dev

          # Install Python packages using pip
          pip3 install cget

          # Install user's private bin path for cget
          CGET_DIR="$HOME/.local/bin"
          PROFILE_DIR="$HOME/.profile"
          # Check if the directory is not already in the profile
          if ! grep -qF "$CGET_DIR" "$PROFILE_DIR"; then
            echo "export PATH=\"\$PATH:$CGET_DIR\"" >> "$PROFILE_DIR"
          fi
          source $PROFILE_DIR

      - name: Display Installed Versions
        run: |
          cmake --version
          g++ --version
          git --version
          python3 --version
          pip3 --version
          cget --version

      - name: Build Libraries
        run: |
          # Install dependencies [JSON, boost] using cget
          cget install https://github.com/nlohmann/json/archive/refs/tags/v3.11.3.tar.gz
          cget install https://github.com/boostorg/boost/releases/download/boost-1.84.0/boost-1.84.0.tar.gz

      - name: Create Archive
        run: tar czf libraries.tar.gz cget
          
      - name: Archive Libraries
        uses: actions/upload-artifact@v3
        with:
          name: libraries
          path: libraries.tar.gz
